<a href="https://colab.research.google.com/github/beyzasakrakdil/ai-chemeng-learning/blob/main/notebooks/01_Python_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 - Python Fundamentals + NumPy + Pandas + Data Cleaning

**Author:** Beyza Şakrakdil

**Based on:** *AI in Chemical Engineering: Unlocking the Power Within Data* (Romagnoli et al.)

This notebook is part of a structured learning path focused on applying machine learning concepts to chemical process data.  
It covers the essential Python foundations, NumPy, Pandas, and a complete workflow for generating and cleaning synthetic process data.

## 1. Python Fundamentals

We start with the absolute basics that will be used in every later notebook.

In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore') #we don't need them right now.

print("Libraries loaded successfully.")
print("NumPy version :", np.__version__)
print("Pandas version:", pd.__version__)

Libraries loaded successfully.
NumPy version : 2.0.2
Pandas version: 2.2.2


In [ ]:
### Variables and Data Types


# Different data types in Python
temperature = 92          # integer
pressure = 3.2            # float
is_running = True         # boolean
reactor_name = "R-101"    # string

print(type(temperature))
print(type(pressure))
print(type(is_running))
print(type(reactor_name))

In [ ]:
### Comparison and Logical Operators

# Comparison operators return True or False
print(temperature > 90 and pressure > 3)          # both conditions must be True
print(temperature > 100 or is_running == False)   # at least one condition True
print(not is_running)                             # reverse the boolean value

In [ ]:
#if, else, elif (means else if)

# Conditional statements control the flow of the program
if temperature > 90:
    print("High temperature → activate cooling system")
elif temperature < 20:
    print("System is too cold, check the process")
else:
    print("Normal operating range")

In [ ]:
### Lists

# A list can store multiple values
temperatures = [75.2, 80.1, 92.5, 88.0, 79.3]

print("First element :", temperatures[0])     # indexing starts from 0
print("Third element :", temperatures[2])
print("Last element  :", temperatures[-1])    # -1 means the last element
print("Third from end:", temperatures[-3])
print("Length of list:", len(temperatures))

# Adding a new value to the end of the list
temperatures.append(95.0)
print("After append  :", temperatures)

In [ ]:
#loops

# A for loop goes through each item in a list one by one
print("Temperature check:")
for t in temperatures:
    if t > 90:
        print(t, "→ High temperature!")
    else:
        print(t, "→ Normal")

In [ ]:
### Functions (print vs return)

# Defining a function
# return gives a value back so we can use it later
def check_temperature(value):
    if value > 90:
        return "High"
    elif value < 20:
        return "Low"
    else:
        return "Normal"

print(check_temperature(95))
print(check_temperature(45))
print(check_temperature(12))

# We can store the returned value in a variable
result = check_temperature(95)
print("Using the returned value:", result + " - trigger alarm")

In [ ]:
#while loop
#while continues as long as the condition is True
counter = 0
while counter < 4:
    print("Counter:", counter)
    counter += 1      # increase the counter (very important!)

Counter: 0
Counter: 1
Counter: 2
Counter: 3


## 2. NumPy

NumPy is the core library for numerical computing.  
Almost every scientific Python library is built on top of it.

In [ ]:
# Creating a simple NumPy array
a = np.array([10, 20, 30, 40, 50])

print("Array:", a)
print("shape :", a.shape)   # how many elements
print("ndim  :", a.ndim)    # number of dimensions
print("dtype :", a.dtype)   # data type of the elements

Array: [10 20 30 40 50]
shape : (5,)
ndim  : 1
dtype : int64


In [ ]:
# Vectorized operations (much faster than normal Python loops)
print(a + 5)
print(a * 2)
print(a / 10)
print(a ** 2)


In [ ]:
# Operations between two arrays (they must have the same shape)
inlet = np.array([70, 75, 80, 85, 90])
outlet = np.array([72, 78, 83, 88, 95])

print("Difference (outlet - inlet):", outlet - inlet)
print("Ratio (outlet / inlet)     :", outlet / inlet)

In [ ]:
# Basic statistics
temp = np.array([72.5, 78.0, 81.3, 79.8, 85.2, 90.1, 76.4])

print("Mean          :", temp.mean())
print("Sum           :", temp.sum())
print("Maximum       :", temp.max())
print("Minimum       :", temp.min())
print("Standard dev. :", temp.std())

In [ ]:
# Slicing (the end index is NOT included)
print("0:3   →", temp[0:3])
print("2:5   →", temp[2:5])
print(":4    →", temp[:4])     # from the beginning
print("3:    →", temp[3:])     # until the end
print("-3:   →", temp[-3:])    # last 3 elements

### Boolean Indexing (Very Important)

In [ ]:
# Boolean indexing lets us select values that meet a condition
print("Greater than 80? →", temp > 80)
print("Values > 80      :", temp[temp > 80])
print("Between 80 and 90:", temp[(temp > 80) & (temp < 90)])

# We can also save the condition as a mask
low_mask = temp < 80
print("Low values:", temp[low_mask])

In [ ]:
# 2D arrays (matrices)
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(matrix)
print("shape:", matrix.shape)
print("ndim :", matrix.ndim)

print("\nColumn sums (axis=0):", matrix.sum(axis=0))
print("Row sums    (axis=1):", matrix.sum(axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
shape: (3, 3)
ndim : 2

Column sums (axis=0): [120 150 180]
Row sums    (axis=1): [ 60 150 240]


In [ ]:
# reshape, stacking and transpose
b = np.arange(12)
print("Original:", b)
print("Reshaped to (3,4):\n", b.reshape(3, 4))

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("\nvstack (vertical):\n", np.vstack((m1, m2)))
print("hstack (horizontal):\n", np.hstack((m1, m2)))

m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nOriginal matrix:\n", m)
print("Transpose:\n", m.T)

In [ ]:
# Element-wise multiplication (*) vs true matrix multiplication (@)
print("Element-wise (*):\n", m1 * m2)
print("True matrix product (@):\n", m1 @ m2)


In [ ]:
# np.where → very useful for conditional replacement
temp2 = np.array([72, 95, 81, 105, 68, 90])

labels = np.where(temp2 > 90, "High", "Normal")
print("Labels:", labels)

# Cap values at 100
capped = np.where(temp2 > 100, 100, temp2)
print("Capped at 100:", capped)

## 3. Pandas

Pandas is the main library for working with tabular data (like Excel, but much more powerful).

In [ ]:
# Creating a DataFrame from a dictionary (cleanest way)
data = {
    "Temperature": [72.5, 85.0, 91.2, 78.3, 95.6],
    "Pressure":    [1.8, 2.1, 2.5, 1.9, 2.8],
    "FlowRate":    [10.2, 11.5, 9.8, 12.0, 10.7]
}
df = pd.DataFrame(data)

print(df)
print("\nShape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nData types:\n", df.dtypes)

   Temperature  Pressure  FlowRate
0         72.5       1.8      10.2
1         85.0       2.1      11.5
2         91.2       2.5       9.8
3         78.3       1.9      12.0
4         95.6       2.8      10.7

Shape: (5, 3)
Columns: ['Temperature', 'Pressure', 'FlowRate']

Data types:
 Temperature    float64
Pressure       float64
FlowRate       float64
dtype: object


In [ ]:
# Quick inspection methods
print("First 3 rows:")
print(df.head(3))

print("\nStatistical summary:")
print(df.describe().T)

# Selecting columns
print("Single column:")
print(df["Temperature"])

print("\nMultiple columns:")
print(df[["Temperature", "Pressure"]])

# Selecting rows
print("First row (by position - iloc):")
print(df.iloc[0])

print("\nRow with index 2 (by label - loc):")
print(df.loc[2])

First 3 rows:
   Temperature  Pressure  FlowRate
0         72.5       1.8      10.2
1         85.0       2.1      11.5
2         91.2       2.5       9.8

Statistical summary:
             count   mean       std   min   25%   50%   75%   max
Temperature    5.0  84.52  9.364668  72.5  78.3  85.0  91.2  95.6
Pressure       5.0   2.22  0.420714   1.8   1.9   2.1   2.5   2.8
FlowRate       5.0  10.84  0.907193   9.8  10.2  10.7  11.5  12.0
Single column:
0    72.5
1    85.0
2    91.2
3    78.3
4    95.6
Name: Temperature, dtype: float64

Multiple columns:
   Temperature  Pressure
0         72.5       1.8
1         85.0       2.1
2         91.2       2.5
3         78.3       1.9
4         95.6       2.8
First row (by position - iloc):
Temperature    72.5
Pressure        1.8
FlowRate       10.2
Name: 0, dtype: float64

Row with index 2 (by label - loc):
Temperature    91.2
Pressure        2.5
FlowRate        9.8
Name: 2, dtype: float64


### Filtering rows (Boolean indexing in Pandas)

In [ ]:
# Filtering is one of the most used operations
print("Rows where Temperature > 85:")
print(df[df["Temperature"] > 85])

print("\nTemperature > 80 AND Pressure < 2.2:")
print(df[(df["Temperature"] > 80) & (df["Pressure"] < 2.2)])

Rows where Temperature > 85:
   Temperature  Pressure  FlowRate
2         91.2       2.5       9.8
4         95.6       2.8      10.7

Temperature > 80 AND Pressure < 2.2:
   Temperature  Pressure  FlowRate
1         85.0       2.1      11.5


## 4. Synthetic Dirty Process Data + Cleaning

Real process data is almost never clean.  
It contains missing values, extreme outliers and physically impossible measurements.

In the next cells we will:
1. Generate realistic synthetic process data
2. Intentionally make it dirty
3. Inspect the problems
4. Clean missing values and outliers

In [3]:
# Set a seed so the results are reproducible
import numpy as np
import pandas as pd

np.random.seed(42)
n = 300

# Create a realistic synthetic process dataset
df = pd.DataFrame({
    'timestamp':     pd.date_range('2024-01-01', periods=n, freq='h'),
    'temperature':   np.random.normal(85, 8, n),
    'pressure':      np.random.normal(2.5, 0.4, n),
    'flow_rate':     np.random.normal(120, 15, n),
    'concentration': np.random.normal(0.45, 0.08, n),
    'reactor_id':    np.random.choice(['R1', 'R2', 'R3'], n),
    'operator':      np.random.choice(['ali', 'ayse', 'mehmet', 'zeynep'], n)
})

# Intentionally make the data dirty (to mimic real process data)
df.loc[10:15, 'temperature'] = np.nan          # missing values
df.loc[50:53, 'pressure'] = np.nan             # missing values
df.loc[100, 'flow_rate'] = 450                 # extreme outlier
df.loc[200, 'concentration'] = -0.1            # physically impossible value
df.loc[250:255, 'temperature'] = 250           # another group of outliers

print("Original shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

Original shape: (300, 7)

Missing values:
timestamp        0
temperature      6
pressure         4
flow_rate        0
concentration    0
reactor_id       0
operator         0
dtype: int64


In [4]:
# Look at the statistics of the dirty data
print("Statistics of the dirty data:")
print(df.describe().T.round(2))

print("\nExtremely high temperatures (>150):")
print(df[df['temperature'] > 150][['temperature', 'pressure', 'flow_rate']].head())

print("\nExtremely high flow rates (>200):")
print(df[df['flow_rate'] > 200][['flow_rate']])

print("\nNegative concentration values:")
print(df[df['concentration'] < 0][['concentration']])

Statistics of the dirty data:
               count                 mean                  min  \
timestamp        300  2024-01-07 05:30:00  2024-01-01 00:00:00   
temperature    294.0            88.433064            59.069861   
pressure       296.0             2.487931             1.511342   
flow_rate      300.0           122.359048              79.5467   
concentration  300.0              0.45577                 -0.1   

                               25%                  50%                  75%  \
timestamp      2024-01-04 02:45:00  2024-01-07 05:30:00  2024-01-10 08:15:00   
temperature              79.722623            85.606705            90.242104   
pressure                  2.209618             2.492016             2.744528   
flow_rate               111.427872           120.862075           130.727503   
concentration             0.405183             0.461336             0.508883   

                               max        std  
timestamp      2024-01-13 11:00:00        Na

In [5]:

# 1. Handling missing values

# Mean is sensitive to outliers → used for temperature
# Median is more robust → used for pressure
df['temperature'] = df['temperature'].fillna(df['temperature'].mean())
df['pressure'] = df['pressure'].fillna(df['pressure'].median())

print("Missing values after imputation:")
print(df.isnull().sum())


# 2. Removing outliers

# Keep only realistic values
df = df[df['temperature'] <= 150]
df = df[df['flow_rate'] <= 200]
df = df[df['concentration'] >= 0]

print("\nShape after cleaning:", df.shape)
print("\nSummary of the cleaned data:")
print(df.describe().T.round(3))

Missing values after imputation:
timestamp        0
temperature      0
pressure         0
flow_rate        0
concentration    0
reactor_id       0
operator         0
dtype: int64

Shape after cleaning: (292, 7)

Summary of the cleaned data:
               count                           mean                  min  \
timestamp        292  2024-01-07 03:22:48.493150464  2024-01-01 00:00:00   
temperature    292.0                      85.165685            59.069861   
pressure       292.0                        2.48682             1.511342   
flow_rate      292.0                     121.233899              79.5467   
concentration  292.0                       0.458101               0.2183   

                               25%                  50%                  75%  \
timestamp      2024-01-04 00:45:00  2024-01-07 02:30:00  2024-01-10 04:15:00   
temperature              79.756452            85.606705            89.921392   
pressure                  2.209618             2.492016       

### Summary of this section

- We created synthetic process data that looks realistic
- We intentionally added missing values and outliers
- We imputed missing values using mean and median
- We removed extreme and physically impossible values using boolean filtering

The data is now clean and ready for the next steps: **Scaling** and **Visualization**.